#!/bin/bash -l
#SBATCH -p development
#SBATCH -t 00:05:00
#SBATCH -N 2
#SBATCH -n 32
#SBATCH --ntasks-per-node=16
#SBATCH -o output/convdiff.%j.out
#SBATCH -e output/convdiff.%j.err

EXEPATH=/home1/04685/tg839843/CS267/final/Local-DG/
EXE=${EXEPATH}driver
NP=$((16*${SLURM_NNODES}))
NPROC=1

OUTPUT=${EXEPATH}output/testOutput.out

echo "running srun -n ${NP} -N ${SLURM_NNODES} ${EXE} > ${OUTPUT}"
ibrun -n ${NP} -o 0 ${EXE} > ${OUTPUT}
tail ${OUTPUT}
